Fix more clang tautological-constant-out-of-range-compare errors.
And one of unused-private-field:
samplecode/SampleStrokeText.cpp:109:10: error: private field 'fAA' is not used [-Werror,-Wunused-private-field]
    bool fAA;

R=bsalomon@google.com,reed@google.com

Review URL: https://codereview.chromium.org/12906016