Explicitly cast to uin16_t to avoid an invalid implicit type narrowing.
This was causing a build failure on OS X for us:

SkOTTable_head.h:124:72: error: non-type template argument evaluates to -2, which cannot be narrowed to type 'uint16_t' (aka 'unsigned short') [-Wc++11-narrowing]

Review URL: https://codereview.appspot.com/6482067