Fix a new clang warning:
third_party/skia/src/ports/SkFontHost_FreeType.cpp:957:7:error: switch case is
in protected scope
      default:
      ^
third_party/skia/src/ports/SkFontHost_FreeType.cpp:918:17: note: jump bypasses
variable initialization
        FT_BBox bbox;
                ^
third_party/skia/src/ports/SkFontHost_FreeType.cpp:946:7:error: switch case is
in protected scope
      case FT_GLYPH_FORMAT_BITMAP:
      ^
third_party/skia/src/ports/SkFontHost_FreeType.cpp:918:17: note: jump bypasses
variable initialization
        FT_BBox bbox;
                ^
2 errors generated.

This is arguably a false positive, but since |bbox| can only safely be used in
the first case branch, it's a good idea to scope it to there anyway. This is
the only instance this warning occurs in all of chrome.

Review URL: http://codereview.appspot.com/4532081/